severs:
  - dev.bar.com
  - foo.bar.com

---
spring.config.activate.on-profile: local
kdt:
  version: "v1.0"
  minimum-order-amount: 1
  support-vendors:
    - a
    - b
    - c
    - d
  description: |-
    line 1 hello world
    line 2 xxxx

---

spring.config.activate.on-profile: dev
kdt:
  version: "v1.0"
  minimum-order-amount: 1
  support-vendors:
    - dev-a
    - dev-b
    - dev-c
    - dev-d
  description: |-
    dev example
    dev description
    


