kdt:
  version: "default-v1.0"
  minimum-order-amount: 1
  support-vendors:
    - default
    - default
    - default
    - default
  description: |-
    this is default properties
    this is default properties
    this is default properties
    this is default properties

  

